#!/bin/sh
# tsp_led

NAME=tsp_led
DESC="TSP display LED"

. /lib/lsb/init-functions

LED_NAME="eng_temp water_temp fuel oil"
GPIO_NUM="21 20 26 16"


start_it_up()
{
  # enable GPIO
  for port in $GPIO_NUM; do
    echo "$port" > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio${port}/direction
    echo "1" > /sys/class/gpio/gpio${port}/value
  done

  log_success_msg "TSP LED GPIO enabled"
}

shut_it_down()
{
  log_daemon_msg "Stopping $DESC" "$NAME"
  # disable GPIO
  for port in $GPIO_NUM; do
    if [ -e /sys/class/gpio/gpio${port} ]; then
      echo "$port" > /sys/class/gpio/unexport
    fi
  done
  log_end_msg $?
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart|reload|force-reload)
    shut_it_down
    start_it_up
  ;;
  status)
   log_success_msg "$DESC" 
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|reload|restart|force-reload|status}" >&2
    exit 2
  ;;
esac

